# Generated by Django 5.0.6 on 2024-05-24 19:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='наименование')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='почта')),
                ('country', models.CharField(blank=True, max_length=100, null=True, verbose_name='страна')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='город')),
                ('street', models.CharField(blank=True, max_length=255, null=True, verbose_name='улица')),
                ('house', models.CharField(blank=True, max_length=32, null=True, verbose_name='номер дома')),
                ('type', models.CharField(choices=[('P', 'завод'), ('R', 'розничная сеть'), ('E', 'индивидуальный предприниматель')], max_length=1, verbose_name='тип компании')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='продукт')),
                ('model', models.CharField(max_length=100, verbose_name='модель')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='описание продукта')),
                ('launch_date', models.DateField(blank=True, null=True, verbose_name='дата выхода на рынок')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='electronet.company', verbose_name='производитель')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
        migrations.CreateModel(
            name='Deliveries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debt', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True, verbose_name='задолженность')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='дата создания')),
                ('level', models.IntegerField(default=1, verbose_name='уровень в иерархии')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipient', to='electronet.company', verbose_name='получатель')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier', to='electronet.company', verbose_name='поставщик')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='electronet.product', verbose_name='продукт')),
            ],
            options={
                'verbose_name': 'Поставка',
                'verbose_name_plural': 'Поставки',
            },
        ),
    ]
