# Generated by Django 5.0.6 on 2024-05-24 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electronet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveries',
            name='debt',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='задолженность'),
        ),
    ]
