# Generated by Django 5.0.6 on 2024-05-24 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('electronet', '0002_alter_deliveries_debt'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'Компания', 'verbose_name_plural': 'Компании'},
        ),
    ]
