# Generated by Django 5.0.6 on 2024-05-25 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electronet', '0003_alter_company_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='model',
            field=models.CharField(max_length=100, unique=True, verbose_name='модель'),
        ),
    ]
