# Generated by Django 5.0.6 on 2024-05-25 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electronet', '0005_debt_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='level',
            field=models.IntegerField(default=0, verbose_name='уровень в иерархии поставок'),
        ),
    ]
