# Generated by Django 5.0.6 on 2024-05-25 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('electronet', '0006_delivery_level'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Delivery',
            new_name='DeliveryNet',
        ),
    ]
