# Generated by Django 5.0.6 on 2024-05-25 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electronet', '0007_rename_delivery_deliverynet'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2024-05-25T00:00:00', verbose_name='время создания'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='сумма поставки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('delivery_net', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='electronet.deliverynet', verbose_name='сеть поставщика')),
            ],
            options={
                'verbose_name': 'Поставка',
                'verbose_name_plural': 'Поставки',
            },
        ),
        migrations.DeleteModel(
            name='Deliveries',
        ),
    ]
