# Generated by Django 5.0.6 on 2024-05-25 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electronet', '0008_company_created_at_delivery_delete_deliveries'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='продукт производится'),
        ),
    ]
