# Generated by Django 5.0.6 on 2024-05-25 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electronet', '0009_product_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='списание задолженности')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='время списания')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_company', to='electronet.company', verbose_name='компания')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_supplier', to='electronet.company', verbose_name='поставщик')),
            ],
            options={
                'verbose_name': 'Списание задолженности',
                'verbose_name_plural': 'Списание задолженностей',
            },
        ),
    ]
