# Generated by Django 5.0.6 on 2024-05-27 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electronet', '0011_delivery_created_by_payment_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='компания активна'),
        ),
        migrations.AddField(
            model_name='deliverynet',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='сеть поставки активна'),
        ),
    ]
